{
 "title": "Real Time Credit Card Fraud Cases Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Distribution of Fraud Transactions by Age",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  age\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\n  AND is_fraud = 1\r\nGROUP BY\r\n  age\r\nORDER BY\r\n  age;"
    }
   ]
  },
  {
   "title": "Fraud Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  merch_lat AS latitude,\r\n  merch_long AS longitude,\r\n  COUNT(*) AS frauds\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\n  AND is_fraud = 1\r\nGROUP BY\r\n  latitude, longitude;\r\n"
    }
   ]
  },
  {
   "title": "Fraud Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n  date_trunc('minute', event_time) AS time,\r\n  ROUND(100.0 * SUM(is_fraud)::decimal / COUNT(*), 2) AS fraud_rate\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1;"
    }
   ]
  },
  {
   "title": "Fraudulent Transactions Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', event_time) AS time,\r\n  SUM(is_fraud) AS frauds\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1;"
    }
   ]
  },
  {
   "title": "Fraud Count by State",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  state,\r\n  COUNT(*)\r\nFROM\r\n  transactions\r\nWHERE\r\n  (\r\n    is_fraud = 1\r\n    AND $__timeFilter(event_time)\r\n  )\r\nGROUP BY\r\n  state\r\n"
    }
   ]
  },
  {
   "title": "Total Number Fraud Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(is_fraud)\r\nFROM\r\n  transactions"
    }
   ]
  },
  {
   "title": "Total amount of Fraud $",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  sum(amt)\r\nfrom\r\n  transactions\r\nwhere\r\n  is_fraud = 1;"
    }
   ]
  },
  {
   "title": "Fraud Count by Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  category,\r\n  COUNT(*) AS frauds\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\n  AND is_fraud = 1\r\nGROUP BY\r\n  category\r\nORDER BY\r\n  frauds DESC;"
    }
   ]
  },
  {
   "title": "Fraud Transactions Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  event_time,\r\n  cc_num,\r\n  merchant,\r\n  category,\r\n  amt,\r\n  city,\r\n  state,\r\n  is_fraud\r\nFROM\r\n  transactions\r\nWHERE\r\n  $__timeFilter(event_time)\r\n  AND is_fraud = 1\r\nORDER BY\r\n  event_time DESC"
    }
   ]
  }
 ]
}